# .github/workflows/publish-navband-visited-ida-plugin.yml
name: publish williballenthin-navband-visited-ida-plugin to pypi

on:
  workflow_dispatch:
  # Example trigger: when a new tag starting with 'navband-visited-v' is pushed
  # push:
  #   tags:
  #     - 'navband-visited-v*'

permissions:
  contents: read
  id-token: write # Required for PyPI trusted publishing

jobs:
  pypi-publish:
    name: build and publish navband_visited
    runs-on: ubuntu-latest
    environment:
      name: release # If using PyPI trusted publishing environments
    permissions:
      id-token: write # Required for PyPI trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Matches requires-python in pyproject.toml

      - name: Install dependencies (build tools)
        run: |
          python -m pip install --upgrade pip
          pip install setuptools build

      - name: Build package
        run: |
          cd plugins/navband_visited
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: plugins/navband_visited/dist

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-navband-visited
          path: plugins/navband_visited/dist/*
